package mqtt

type ReasonCode byte

var (
	BASE_SUCCESS = 0x00
)

var (
	V3_CONNACK_ACCEPT                ReasonCode = 0x00
	V3_CONNACK_UNACCEPTABLE_VERSION  ReasonCode = 0x01
	V3_CONNACK_INDENTIFIER_REJECT    ReasonCode = 0x02
	V3_CONNACK_SERVER_UNAVAILABLE    ReasonCode = 0x03
	V3_CONNACK_BAD_USERNAME_PASSWORD ReasonCode = 0x04
	V3_CONNACK_NOT_AUTHORIZED        ReasonCode = 0x05
)

var (
	V5_CONACK_SUCCESS ReasonCode = 0x00

	V5_PUBACK_NO_MATCH_SUBSCRIBERS          = 0x10
	V5_PUBACK_UNSPECIFIED_ERROR             = 0x80
	V5_PUBACK_IMPLEMENTATION_SPECIFIC_ERROR = 0x83
	V5_PUBACK_NOT_AUTHORIZED                = 0x87
	V5_PUBACK_TOPIC_NAME_INVALID            = 0x90
	V5_PUBACK_PACKET_IDENTIFIER_IN_USE      = 0x91
	V5_PUBACK_QUOTA_EXCEEDED                = 0x97
	V5_PUBACK_PAYLOAD_FORMAT_INVALID        = 0x99
)
